name: sitespeed.io extra action example
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:25.1.1 https://www.sitespeed.io -n 1 